spring.application.name=rate_limiter
spring.profiles.active:local
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.metrics.enabled=true
rate-limiter.window-ms=10000
rate-limiter.max-requests=3
rate-limiter.excluded-paths=/actuator,/swagger,/v3/api-docs,/health
spring.data.redis.timeout=100ms
spring.data.redis.connect-timeout=100ms

